version: "3"

services:

  runtime-setup:
    image: swift-metrics:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: swift-metrics:22.04-main
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-metrics:22.04-main
